<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <RootNamespace>HostedToolbox</RootNamespace>
    <AssemblyName>HostedToolbox</AssemblyName>
    <NoWarn>$(NoWarn);</NoWarn>
    <UserSecretsId>4f1bafc1-533b-44aa-be01-19a4641b96b7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.Agents.AI.Foundry.Hosting" Version="1.15.0-preview.260722.1" />
  </ItemGroup>

</Project>
